name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true
      - name: Build
        run: sudo nix run .#nixosConfigurations.nixos.config.system.build.tarballBuilder
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: nixos-wsl.tar.gz